window.VIEWER_DEMO_DATA = {
  "generatedAt": "2026-04-04T01:23:02.948Z",
  "referenceName": "Renato",
  "dayHours": 9.5,
  "technicians": [
    {
      "id": "UTLME005",
      "name": "Carlos Augusto",
      "shift": "Mecanico de Manutencao Industrial"
    },
    {
      "id": "UTLME008",
      "name": "Fernando Roque",
      "shift": "Eletromecanico de Manutencao Industrial"
    },
    {
      "id": "UTLRE007",
      "name": "Patrick Rosario",
      "shift": "Eletromecanico de Refrigeracao Industrial"
    }
  ],
  "months": {
    "2026-03": {
      "monthlyTarget": 141,
      "orders": [
        {
          "id": 4,
          "orderNumber": "10651716",
          "orderType": "Corretiva",
          "sector": "CREMES",
          "equipment": "ELEVADOR CCME",
          "tag": "ELE01009",
          "technicianId": "UTLME008",
          "date": "2026-03-02",
          "startTime": "23:00",
          "endTime": "23:50",
          "executedHours": 0.8333333333333334,
          "activity": "Pallet travado mesa elevacao",
          "observation": "Pallet travado na mesa de elevacao. Atendimento corretivo e liberacao do equipamento."
        },
        {
          "id": 6,
          "orderNumber": "10652393",
          "orderType": "Corretiva",
          "sector": "CENTRO DE PESQUISA",
          "equipment": "BOMBA CAIXA KOPLER",
          "tag": "MOB01746",
          "technicianId": "UTLME008",
          "date": "2026-03-03",
          "startTime": "18:00",
          "endTime": "20:30",
          "executedHours": 2.5,
          "activity": "Teste para ligar bomba",
          "observation": "Teste operacional realizado para partida da bomba e validacao do funcionamento."
        },
        {
          "id": 5,
          "orderNumber": "10652248",
          "orderType": "Corretiva",
          "sector": "CREMES",
          "equipment": "ELEVADOR CCME",
          "tag": "ELE01009",
          "technicianId": "UTLME008",
          "date": "2026-03-03",
          "startTime": "20:40",
          "endTime": "21:20",
          "executedHours": 0.6666666666666666,
          "activity": "Pallet travado mesa elevacao",
          "observation": "Destravamento de pallet na mesa de elevacao e restabelecimento da operacao."
        },
        {
          "id": 7,
          "orderNumber": "10652330",
          "orderType": "Corretiva",
          "sector": "ESCALONAMENTO",
          "equipment": "ELEVADOR 1",
          "tag": "ELE01616",
          "technicianId": "UTLME008",
          "date": "2026-03-03",
          "startTime": "21:50",
          "endTime": "23:20",
          "executedHours": 1.5,
          "activity": "Porta travada fora do trilho",
          "observation": "Ajuste de porta travada fora do trilho com retorno do elevador para operacao."
        },
        {
          "id": 8,
          "orderNumber": "10652511",
          "orderType": "Corretiva",
          "sector": "ESCALONAMENTO",
          "equipment": "ELEVADOR 1",
          "tag": "ELE01009",
          "technicianId": "UTLME008",
          "date": "2026-03-04",
          "startTime": "20:30",
          "endTime": "21:15",
          "executedHours": 0.75,
          "activity": "Pallet travado mesa elevacao",
          "observation": "Atendimento para destravar pallet na mesa de elevacao."
        },
        {
          "id": 9,
          "orderNumber": "10652513",
          "orderType": "Corretiva",
          "sector": "ESCALONAMENTO",
          "equipment": "ELEVADOR 1",
          "tag": "ELE01009",
          "technicianId": "UTLME008",
          "date": "2026-03-04",
          "startTime": "22:00",
          "endTime": "22:45",
          "executedHours": 0.75,
          "activity": "Pallet travado mesa elevacao",
          "observation": "Novo atendimento de pallet travado na mesa de elevacao."
        },
        {
          "id": 10,
          "orderNumber": "10652512",
          "orderType": "Corretiva",
          "sector": "ESCALONAMENTO",
          "equipment": "ELEVADOR 1",
          "tag": "ELE01009",
          "technicianId": "UTLME008",
          "date": "2026-03-04",
          "startTime": "22:00",
          "endTime": "22:45",
          "executedHours": 0.75,
          "activity": "Pallet travado mesa elevacao",
          "observation": "Atendimento adicional em ocorrencia similar de pallet travado."
        },
        {
          "id": 11,
          "orderNumber": "10653339",
          "orderType": "Corretiva",
          "sector": "HIDRO",
          "equipment": "ELEVADOR DO HIDRO",
          "tag": "ELE01012",
          "technicianId": "UTLME008",
          "date": "2026-03-09",
          "startTime": "18:30",
          "endTime": "19:30",
          "executedHours": 1,
          "activity": "Pallet travado na mesa",
          "observation": "Correcao de pallet travado na mesa do elevador do Hidro."
        },
        {
          "id": 12,
          "orderNumber": "10653393",
          "orderType": "Corretiva",
          "sector": "ESCALONAMENTO",
          "equipment": "ELEVADOR 3P 02",
          "tag": "ELE01617",
          "technicianId": "UTLME008",
          "date": "2026-03-09",
          "startTime": "20:00",
          "endTime": "20:50",
          "executedHours": 0.8333333333333334,
          "activity": "Reset do elevador e ajuste de botao de emergencia",
          "observation": "Reset do elevador e tratamento de mau contato no botao de emergencia."
        },
        {
          "id": 13,
          "orderNumber": "10653394",
          "orderType": "Corretiva",
          "sector": "CREMES",
          "equipment": "ELEVADOR 2P 02",
          "tag": "AGI01788",
          "technicianId": "UTLME008",
          "date": "2026-03-10",
          "startTime": "00:00",
          "endTime": "01:20",
          "executedHours": 1.3333333333333333,
          "activity": "Ajuste rele de seguranca porta",
          "observation": "Ajuste do rele de seguranca da porta e teste funcional do equipamento."
        },
        {
          "id": 14,
          "orderNumber": "10653395",
          "orderType": "Corretiva",
          "sector": "CREMES",
          "equipment": "ELEVADOR CCME",
          "tag": "ELE01009",
          "technicianId": "UTLME008",
          "date": "2026-03-10",
          "startTime": "01:20",
          "endTime": "03:00",
          "executedHours": 1.67,
          "activity": "Apoio a resgate de pessoas presas no elevador",
          "observation": "Apoio ao resgate de pessoas presas no elevador com liberacao segura."
        },
        {
          "id": 15,
          "orderNumber": "10653742",
          "orderType": "Corretiva",
          "sector": "CREMES",
          "equipment": "ELEVADOR CCME",
          "tag": "ELE01009",
          "technicianId": "UTLME008",
          "date": "2026-03-10",
          "startTime": "18:00",
          "endTime": "00:00",
          "executedHours": 6,
          "activity": "Instalacao de motor e teste",
          "observation": "Instalacao de motor no elevador CCME e realizacao de testes de funcionamento."
        },
        {
          "id": 16,
          "orderNumber": "10653743",
          "orderType": "Corretiva",
          "sector": "ETE",
          "equipment": "BOMBA SUBMERSA TANQUE POLIMENTO",
          "tag": "TAN01714",
          "technicianId": "UTLME008",
          "date": "2026-03-11",
          "startTime": "00:10",
          "endTime": "04:12",
          "executedHours": 4.03,
          "activity": "Troca de motobomba ajuste",
          "observation": "Substituicao da motobomba do tanque de polimento e verificacao operacional."
        },
        {
          "id": 24,
          "orderNumber": "24033101",
          "orderType": "Corretiva",
          "sector": "HIDRO",
          "equipment": "Elevador Separacao",
          "tag": "ELE1010",
          "technicianId": "UTLME008",
          "date": "2026-03-24",
          "startTime": "07:30",
          "endTime": "09:00",
          "executedHours": 1.5,
          "activity": "Ajuste de esteira principal",
          "observation": "Teste automatizado 1 para validar historico e KPI."
        },
        {
          "id": 25,
          "orderNumber": "24033102",
          "orderType": "Preventiva",
          "sector": "CREMES",
          "equipment": "ELEVADOR CCME",
          "tag": "ELE01009",
          "technicianId": "UTLME008",
          "date": "2026-03-25",
          "startTime": "08:10",
          "endTime": "10:40",
          "executedHours": 2.5,
          "activity": "Inspecao preventiva no elevador",
          "observation": "Teste automatizado 2 para validar grafico por data."
        },
        {
          "id": 26,
          "orderNumber": "24033103",
          "orderType": "Corretiva",
          "sector": "HIDRO",
          "equipment": "ELEVADOR DO HIDRO",
          "tag": "ELE01012",
          "technicianId": "UTLME008",
          "date": "2026-03-26",
          "startTime": "13:15",
          "endTime": "15:00",
          "executedHours": 1.75,
          "activity": "Correcao de falha no conjunto",
          "observation": "Teste automatizado 3 para validar acumulado mensal."
        },
        {
          "id": 27,
          "orderNumber": "24033104",
          "orderType": "Corretiva",
          "sector": "ESCALONAMENTO",
          "equipment": "ELEVADOR 1",
          "tag": "ELE01616",
          "technicianId": "UTLME008",
          "date": "2026-03-27",
          "startTime": "23:30",
          "endTime": "00:30",
          "executedHours": 1,
          "activity": "Reinicio e teste do acionamento",
          "observation": "Teste automatizado 4 para validar virada de dia no historico."
        }
      ]
    },
    "2026-04": {
      "monthlyTarget": 142.5,
      "orders": [
        {
          "id": 39,
          "orderNumber": "10660482",
          "orderType": "Corretiva",
          "sector": "ETE",
          "equipment": "FILTRO PRENSA",
          "tag": "FIL01601",
          "technicianId": "UTLME008",
          "date": "2026-04-01",
          "startTime": "18:10",
          "endTime": "20:00",
          "executedHours": 1.83,
          "activity": "Verificação do filtro prensa",
          "observation": "Auxílio na correção do equipamento não estar funcionando"
        },
        {
          "id": 41,
          "orderNumber": "10660482",
          "orderType": "Corretiva",
          "sector": "ETE",
          "equipment": "FILTRO PRENSA",
          "tag": "FIL01601",
          "technicianId": "UTLME005",
          "date": "2026-04-01",
          "startTime": "18:10",
          "endTime": "20:00",
          "executedHours": 1.83,
          "activity": "Verificação do filtro prensa",
          "observation": "Auxílio na correção do equipamento que não está funcionando."
        },
        {
          "id": 38,
          "orderNumber": "10660505",
          "orderType": "Corretiva",
          "sector": "CREMES",
          "equipment": "ELEVADOR CCME",
          "tag": "ELE01009",
          "technicianId": "UTLME008",
          "date": "2026-04-01",
          "startTime": "20:00",
          "endTime": "21:30",
          "executedHours": 1.5,
          "activity": "Limpeza no sensor da mesa de elevação",
          "observation": "Realizada limpeza do sensor, identificando-se que o acúmulo de sujeira estava impedindo o acionamento correto do sistema, o que ocasionava a falha de subida da mesa de elevação; após a intervenção, o equipamento foi testado e retornou ao funcionamento normal, operando conforme o esperado."
        },
        {
          "id": 40,
          "orderNumber": "10648807",
          "orderType": "Preventiva",
          "sector": "UTILIDADES 1",
          "equipment": "MOTOBOMBA VERDE CIS. 1 E 2",
          "tag": "MOB01805",
          "technicianId": "UTLME005",
          "date": "2026-04-01",
          "startTime": "20:10",
          "endTime": "05:10",
          "executedHours": 9,
          "activity": "Preventiva de bombas nas cisternas scorpion,1,2,3,4 e 5",
          "observation": "Realizado verificação do equipamento e notificação de anormalidades"
        },
        {
          "id": 42,
          "orderNumber": "10660813",
          "orderType": "Corretiva",
          "sector": "UTILIDADES 1",
          "equipment": "MOTOBOMBA VERDE CIS. 1 E 2",
          "tag": "MOB01805",
          "technicianId": "UTLME005",
          "date": "2026-04-02",
          "startTime": "18:00",
          "endTime": "04:30",
          "executedHours": 10.5,
          "activity": "Reparo de tubulação com vazamento",
          "observation": "Realizado troca parcial da tubulação que estava com a rosca da união gasta"
        },
        {
          "id": 44,
          "orderNumber": "10648803",
          "orderType": "Corretiva",
          "sector": "UTILIDADES 1",
          "equipment": "MOTOBOMBA VERDE CIS. 1 E 2",
          "tag": "MOB01805",
          "technicianId": "UTLME008",
          "date": "2026-04-02",
          "startTime": "18:00",
          "endTime": "04:30",
          "executedHours": 10.5,
          "activity": "Reparo de tubulação com vazamento",
          "observation": "Realizado troca parcial da tubulação que estava com a rosca da união gasta"
        },
        {
          "id": 45,
          "orderNumber": "10648803",
          "orderType": "Corretiva",
          "sector": "UTILIDADES 1",
          "equipment": "MOTOBOMBA VERDE CIS. 1 E 2",
          "tag": "MOB01805",
          "technicianId": "UTLRE007",
          "date": "2026-04-02",
          "startTime": "18:00",
          "endTime": "04:30",
          "executedHours": 10.5,
          "activity": "Reparo de tubulação com vazamento",
          "observation": "Realizado troca parcial da tubulação que estava com a rosca da união gasta"
        },
        {
          "id": 43,
          "orderNumber": "10660814",
          "orderType": "Corretiva",
          "sector": "HIDRO",
          "equipment": "ELEVADOR DO HIDRO",
          "tag": "ELE01012",
          "technicianId": "UTLME005",
          "date": "2026-04-03",
          "startTime": "04:30",
          "endTime": "05:30",
          "executedHours": 1,
          "activity": "Problema na cortina de luz",
          "observation": "Realizado alinhamento da cortina de luz do elevador"
        }
      ]
    }
  }
}
