window.VIEWER_DEMO_DATA = {
  "generatedAt": "2026-04-22T08:17:02.662Z",
  "referenceName": "Renato",
  "dayHours": 9.5,
  "technicians": [
    {
      "id": "UTLME005",
      "name": "Carlos Augusto",
      "shift": "Mecanico de Manutencao Industrial"
    },
    {
      "id": "UTLME008",
      "name": "Fernando Roque",
      "shift": "Eletromecanico de Manutencao Industrial"
    },
    {
      "id": "UTLRE007",
      "name": "Patrick Rosario",
      "shift": "Eletromecanico de Refrigeracao Industrial"
    }
  ],
  "months": {
    "2026-03": {
      "monthlyTarget": 141,
      "orders": [
        {
          "id": 4,
          "orderNumber": "10651716",
          "orderType": "Corretiva",
          "sector": "CREMES",
          "equipment": "ELEVADOR CCME",
          "tag": "ELE01009",
          "technicianId": "UTLME008",
          "date": "2026-03-02",
          "startTime": "23:00",
          "endTime": "23:50",
          "executedHours": 0.8333333333333334,
          "activity": "Pallet travado mesa elevacao",
          "observation": "Pallet travado na mesa de elevacao. Atendimento corretivo e liberacao do equipamento."
        },
        {
          "id": 6,
          "orderNumber": "10652393",
          "orderType": "Corretiva",
          "sector": "CENTRO DE PESQUISA",
          "equipment": "BOMBA CAIXA KOPLER",
          "tag": "MOB01746",
          "technicianId": "UTLME008",
          "date": "2026-03-03",
          "startTime": "18:00",
          "endTime": "20:30",
          "executedHours": 2.5,
          "activity": "Teste para ligar bomba",
          "observation": "Teste operacional realizado para partida da bomba e validacao do funcionamento."
        },
        {
          "id": 5,
          "orderNumber": "10652248",
          "orderType": "Corretiva",
          "sector": "CREMES",
          "equipment": "ELEVADOR CCME",
          "tag": "ELE01009",
          "technicianId": "UTLME008",
          "date": "2026-03-03",
          "startTime": "20:40",
          "endTime": "21:20",
          "executedHours": 0.6666666666666666,
          "activity": "Pallet travado mesa elevacao",
          "observation": "Destravamento de pallet na mesa de elevacao e restabelecimento da operacao."
        },
        {
          "id": 7,
          "orderNumber": "10652330",
          "orderType": "Corretiva",
          "sector": "ESCALONAMENTO",
          "equipment": "ELEVADOR 1",
          "tag": "ELE01616",
          "technicianId": "UTLME008",
          "date": "2026-03-03",
          "startTime": "21:50",
          "endTime": "23:20",
          "executedHours": 1.5,
          "activity": "Porta travada fora do trilho",
          "observation": "Ajuste de porta travada fora do trilho com retorno do elevador para operacao."
        },
        {
          "id": 8,
          "orderNumber": "10652511",
          "orderType": "Corretiva",
          "sector": "ESCALONAMENTO",
          "equipment": "ELEVADOR 1",
          "tag": "ELE01009",
          "technicianId": "UTLME008",
          "date": "2026-03-04",
          "startTime": "20:30",
          "endTime": "21:15",
          "executedHours": 0.75,
          "activity": "Pallet travado mesa elevacao",
          "observation": "Atendimento para destravar pallet na mesa de elevacao."
        },
        {
          "id": 9,
          "orderNumber": "10652513",
          "orderType": "Corretiva",
          "sector": "ESCALONAMENTO",
          "equipment": "ELEVADOR 1",
          "tag": "ELE01009",
          "technicianId": "UTLME008",
          "date": "2026-03-04",
          "startTime": "22:00",
          "endTime": "22:45",
          "executedHours": 0.75,
          "activity": "Pallet travado mesa elevacao",
          "observation": "Novo atendimento de pallet travado na mesa de elevacao."
        },
        {
          "id": 10,
          "orderNumber": "10652512",
          "orderType": "Corretiva",
          "sector": "ESCALONAMENTO",
          "equipment": "ELEVADOR 1",
          "tag": "ELE01009",
          "technicianId": "UTLME008",
          "date": "2026-03-04",
          "startTime": "22:00",
          "endTime": "22:45",
          "executedHours": 0.75,
          "activity": "Pallet travado mesa elevacao",
          "observation": "Atendimento adicional em ocorrencia similar de pallet travado."
        },
        {
          "id": 11,
          "orderNumber": "10653339",
          "orderType": "Corretiva",
          "sector": "HIDRO",
          "equipment": "ELEVADOR DO HIDRO",
          "tag": "ELE01012",
          "technicianId": "UTLME008",
          "date": "2026-03-09",
          "startTime": "18:30",
          "endTime": "19:30",
          "executedHours": 1,
          "activity": "Pallet travado na mesa",
          "observation": "Correcao de pallet travado na mesa do elevador do Hidro."
        },
        {
          "id": 12,
          "orderNumber": "10653393",
          "orderType": "Corretiva",
          "sector": "ESCALONAMENTO",
          "equipment": "ELEVADOR 3P 02",
          "tag": "ELE01617",
          "technicianId": "UTLME008",
          "date": "2026-03-09",
          "startTime": "20:00",
          "endTime": "20:50",
          "executedHours": 0.8333333333333334,
          "activity": "Reset do elevador e ajuste de botao de emergencia",
          "observation": "Reset do elevador e tratamento de mau contato no botao de emergencia."
        },
        {
          "id": 13,
          "orderNumber": "10653394",
          "orderType": "Corretiva",
          "sector": "CREMES",
          "equipment": "ELEVADOR 2P 02",
          "tag": "ELE01614",
          "technicianId": "UTLME008",
          "date": "2026-03-10",
          "startTime": "00:00",
          "endTime": "01:20",
          "executedHours": 1.3333333333333333,
          "activity": "Ajuste rele de seguranca porta",
          "observation": "Ajuste do rele de seguranca da porta e teste funcional do equipamento."
        },
        {
          "id": 14,
          "orderNumber": "10653395",
          "orderType": "Corretiva",
          "sector": "CREMES",
          "equipment": "ELEVADOR CCME",
          "tag": "ELE01009",
          "technicianId": "UTLME008",
          "date": "2026-03-10",
          "startTime": "01:20",
          "endTime": "03:00",
          "executedHours": 1.67,
          "activity": "Apoio a resgate de pessoas presas no elevador",
          "observation": "Apoio ao resgate de pessoas presas no elevador com liberacao segura."
        },
        {
          "id": 15,
          "orderNumber": "10653742",
          "orderType": "Corretiva",
          "sector": "CREMES",
          "equipment": "ELEVADOR CCME",
          "tag": "ELE01009",
          "technicianId": "UTLME008",
          "date": "2026-03-10",
          "startTime": "18:00",
          "endTime": "00:00",
          "executedHours": 6,
          "activity": "Instalacao de motor e teste",
          "observation": "Instalacao de motor no elevador CCME e realizacao de testes de funcionamento."
        },
        {
          "id": 16,
          "orderNumber": "10653743",
          "orderType": "Corretiva",
          "sector": "ETE",
          "equipment": "BOMBA SUBMERSA TANQUE POLIMENTO",
          "tag": "TAN01714",
          "technicianId": "UTLME008",
          "date": "2026-03-11",
          "startTime": "00:10",
          "endTime": "04:12",
          "executedHours": 4.03,
          "activity": "Troca de motobomba ajuste",
          "observation": "Substituicao da motobomba do tanque de polimento e verificacao operacional."
        },
        {
          "id": 24,
          "orderNumber": "24033101",
          "orderType": "Corretiva",
          "sector": "HIDRO",
          "equipment": "ELEVADOR SEPARACAO",
          "tag": "ELE01010",
          "technicianId": "UTLME008",
          "date": "2026-03-24",
          "startTime": "07:30",
          "endTime": "09:00",
          "executedHours": 1.5,
          "activity": "Ajuste de esteira principal",
          "observation": "Teste automatizado 1 para validar historico e KPI."
        },
        {
          "id": 25,
          "orderNumber": "24033102",
          "orderType": "Preventiva",
          "sector": "CREMES",
          "equipment": "ELEVADOR CCME",
          "tag": "ELE01009",
          "technicianId": "UTLME008",
          "date": "2026-03-25",
          "startTime": "08:10",
          "endTime": "10:40",
          "executedHours": 2.5,
          "activity": "Inspecao preventiva no elevador",
          "observation": "Teste automatizado 2 para validar grafico por data."
        },
        {
          "id": 26,
          "orderNumber": "24033103",
          "orderType": "Corretiva",
          "sector": "HIDRO",
          "equipment": "ELEVADOR DO HIDRO",
          "tag": "ELE01012",
          "technicianId": "UTLME008",
          "date": "2026-03-26",
          "startTime": "13:15",
          "endTime": "15:00",
          "executedHours": 1.75,
          "activity": "Correcao de falha no conjunto",
          "observation": "Teste automatizado 3 para validar acumulado mensal."
        },
        {
          "id": 27,
          "orderNumber": "24033104",
          "orderType": "Corretiva",
          "sector": "ESCALONAMENTO",
          "equipment": "ELEVADOR 1",
          "tag": "ELE01616",
          "technicianId": "UTLME008",
          "date": "2026-03-27",
          "startTime": "23:30",
          "endTime": "00:30",
          "executedHours": 1,
          "activity": "Reinicio e teste do acionamento",
          "observation": "Teste automatizado 4 para validar virada de dia no historico."
        }
      ]
    },
    "2026-04": {
      "monthlyTarget": 142.5,
      "orders": [
        {
          "id": 52,
          "orderNumber": "10658697",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01600",
          "technicianId": "UTLRE007",
          "date": "2026-04-01",
          "startTime": "18:00",
          "endTime": "19:34",
          "executedHours": 1.57,
          "activity": "PREVENTIVA",
          "observation": "OBS:BEX01600"
        },
        {
          "id": 39,
          "orderNumber": "10660482",
          "orderType": "Corretiva",
          "sector": "ETE",
          "equipment": "FILTRO PRENSA",
          "tag": "FIL01601",
          "technicianId": "UTLME008",
          "date": "2026-04-01",
          "startTime": "18:10",
          "endTime": "20:00",
          "executedHours": 1.83,
          "activity": "Verificação do filtro prensa",
          "observation": "Auxílio na correção do equipamento não estar funcionando"
        },
        {
          "id": 41,
          "orderNumber": "10660482",
          "orderType": "Corretiva",
          "sector": "ETE",
          "equipment": "FILTRO PRENSA",
          "tag": "FIL01601",
          "technicianId": "UTLME005",
          "date": "2026-04-01",
          "startTime": "18:10",
          "endTime": "20:00",
          "executedHours": 1.83,
          "activity": "Verificação do filtro prensa",
          "observation": "Auxílio na correção do equipamento que não está funcionando."
        },
        {
          "id": 51,
          "orderNumber": "10658698",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01601",
          "technicianId": "UTLRE007",
          "date": "2026-04-01",
          "startTime": "19:34",
          "endTime": "21:08",
          "executedHours": 1.57,
          "activity": "PREVENTIVA",
          "observation": "OBS:BEX01601"
        },
        {
          "id": 38,
          "orderNumber": "10660505",
          "orderType": "Corretiva",
          "sector": "CREMES",
          "equipment": "ELEVADOR CCME",
          "tag": "ELE01009",
          "technicianId": "UTLME008",
          "date": "2026-04-01",
          "startTime": "20:00",
          "endTime": "21:30",
          "executedHours": 1.5,
          "activity": "Limpeza no sensor da mesa de elevação",
          "observation": "Realizada limpeza do sensor, identificando-se que o acúmulo de sujeira estava impedindo o acionamento correto do sistema, o que ocasionava a falha de subida da mesa de elevação; após a intervenção, o equipamento foi testado e retornou ao funcionamento normal, operando conforme o esperado."
        },
        {
          "id": 40,
          "orderNumber": "10648807",
          "orderType": "Preventiva",
          "sector": "UTILIDADES 1",
          "equipment": "MOTOBOMBA VERDE CIS. 1 E 2",
          "tag": "MOB01805",
          "technicianId": "UTLME005",
          "date": "2026-04-01",
          "startTime": "20:10",
          "endTime": "05:10",
          "executedHours": 9,
          "activity": "Preventiva de bombas nas cisternas scorpion,1,2,3,4 e 5",
          "observation": "Realizado verificação do equipamento e notificação de anormalidades"
        },
        {
          "id": 53,
          "orderNumber": "10658699",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01602",
          "technicianId": "UTLRE007",
          "date": "2026-04-01",
          "startTime": "21:34",
          "endTime": "23:10",
          "executedHours": 1.6,
          "activity": "PREVENTIVA",
          "observation": "OBS:BEX01602"
        },
        {
          "id": 54,
          "orderNumber": "10658700",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01603",
          "technicianId": "UTLRE007",
          "date": "2026-04-01",
          "startTime": "23:10",
          "endTime": "23:53",
          "executedHours": 0.72,
          "activity": "PREVENTIVA",
          "observation": "OBS:BEX01603"
        },
        {
          "id": 58,
          "orderNumber": "10658701",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01604",
          "technicianId": "UTLRE007",
          "date": "2026-04-02",
          "startTime": "01:00",
          "endTime": "02:32",
          "executedHours": 1.53,
          "activity": "PREVENTIVA",
          "observation": "OBS:BEX01604"
        },
        {
          "id": 55,
          "orderNumber": "10658730",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01636",
          "technicianId": "UTLRE007",
          "date": "2026-04-02",
          "startTime": "02:32",
          "endTime": "04:04",
          "executedHours": 1.53,
          "activity": "PREVENTIVA",
          "observation": "OBS:BEX01636"
        },
        {
          "id": 56,
          "orderNumber": "10658729",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01635",
          "technicianId": "UTLRE007",
          "date": "2026-04-02",
          "startTime": "04:05",
          "endTime": "05:13",
          "executedHours": 1.13,
          "activity": "PREVENTIVA",
          "observation": "OBS:BEX01635"
        },
        {
          "id": 57,
          "orderNumber": "10658728",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01634",
          "technicianId": "UTLRE007",
          "date": "2026-04-02",
          "startTime": "05:13",
          "endTime": "05:51",
          "executedHours": 0.63,
          "activity": "PREVENTIVA",
          "observation": "OBS:BEX01634"
        },
        {
          "id": 42,
          "orderNumber": "10660813",
          "orderType": "Corretiva",
          "sector": "UTILIDADES 1",
          "equipment": "MOTOBOMBA VERDE CIS. 1 E 2",
          "tag": "MOB01805",
          "technicianId": "UTLME005",
          "date": "2026-04-02",
          "startTime": "18:00",
          "endTime": "04:30",
          "executedHours": 10.5,
          "activity": "Reparo de tubulação com vazamento",
          "observation": "Realizado troca parcial da tubulação que estava com a rosca da união gasta"
        },
        {
          "id": 44,
          "orderNumber": "10648803",
          "orderType": "Corretiva",
          "sector": "UTILIDADES 1",
          "equipment": "MOTOBOMBA VERDE CIS. 1 E 2",
          "tag": "MOB01805",
          "technicianId": "UTLME008",
          "date": "2026-04-02",
          "startTime": "18:00",
          "endTime": "04:30",
          "executedHours": 10.5,
          "activity": "Reparo de tubulação com vazamento",
          "observation": "Realizado troca parcial da tubulação que estava com a rosca da união gasta"
        },
        {
          "id": 45,
          "orderNumber": "10648803",
          "orderType": "Corretiva",
          "sector": "UTILIDADES 1",
          "equipment": "MOTOBOMBA VERDE CIS. 1 E 2",
          "tag": "MOB01805",
          "technicianId": "UTLRE007",
          "date": "2026-04-02",
          "startTime": "18:00",
          "endTime": "04:30",
          "executedHours": 10.5,
          "activity": "Reparo de tubulação com vazamento",
          "observation": "Realizado troca parcial da tubulação que estava com a rosca da união gasta"
        },
        {
          "id": 43,
          "orderNumber": "10660814",
          "orderType": "Corretiva",
          "sector": "HIDRO",
          "equipment": "ELEVADOR DO HIDRO",
          "tag": "ELE01012",
          "technicianId": "UTLME005",
          "date": "2026-04-03",
          "startTime": "04:30",
          "endTime": "05:30",
          "executedHours": 1,
          "activity": "Problema na cortina de luz",
          "observation": "Realizado alinhamento da cortina de luz do elevador"
        },
        {
          "id": 46,
          "orderNumber": "10660814",
          "orderType": "Corretiva",
          "sector": "HIDRO",
          "equipment": "ELEVADOR DO HIDRO",
          "tag": "ELE01012",
          "technicianId": "UTLRE007",
          "date": "2026-04-03",
          "startTime": "04:30",
          "endTime": "05:30",
          "executedHours": 1,
          "activity": "Realizado alinhamento da cortina de luz do elevador",
          "observation": ""
        },
        {
          "id": 68,
          "orderNumber": "10660814",
          "orderType": "Corretiva",
          "sector": "HIDRO",
          "equipment": "ELEVADOR DO HIDRO",
          "tag": "ELE01012",
          "technicianId": "UTLME008",
          "date": "2026-04-03",
          "startTime": "04:30",
          "endTime": "05:30",
          "executedHours": 1,
          "activity": "Elevador de carga travado",
          "observation": "Realizado destravamento do elevador de carga e liberado para operacao."
        },
        {
          "id": 47,
          "orderNumber": "10658731",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01637",
          "technicianId": "UTLRE007",
          "date": "2026-04-03",
          "startTime": "18:00",
          "endTime": "19:36",
          "executedHours": 1.6,
          "activity": "PREVENTIVA",
          "observation": "OBS:BEX01637"
        },
        {
          "id": 61,
          "orderNumber": "10660853",
          "orderType": "Preventiva",
          "sector": "ETE",
          "equipment": "COMPRESSOR SOPRADOR 3",
          "tag": "COM01607",
          "technicianId": "UTLME008",
          "date": "2026-04-03",
          "startTime": "18:00",
          "endTime": "00:00",
          "executedHours": 6,
          "activity": "Bloqueio de energia para manutenção preventiva",
          "observation": "Feito bloqueio elétrico para mecânico fazer preventivas nos sopradores 3 e 4."
        },
        {
          "id": 48,
          "orderNumber": "10658732",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01638",
          "technicianId": "UTLRE007",
          "date": "2026-04-03",
          "startTime": "19:36",
          "endTime": "21:12",
          "executedHours": 1.6,
          "activity": "PREVENTIVA",
          "observation": "OBS:BEX01638"
        },
        {
          "id": 49,
          "orderNumber": "10658733",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01639",
          "technicianId": "UTLRE007",
          "date": "2026-04-03",
          "startTime": "21:12",
          "endTime": "22:14",
          "executedHours": 1.03,
          "activity": "PREVENTIVA",
          "observation": "OBS:BEX01639"
        },
        {
          "id": 50,
          "orderNumber": "10658734",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01640",
          "technicianId": "UTLRE007",
          "date": "2026-04-03",
          "startTime": "22:14",
          "endTime": "23:19",
          "executedHours": 1.08,
          "activity": "PREVENTIVA",
          "observation": "OBS:BEX01640"
        },
        {
          "id": 63,
          "orderNumber": "10660854",
          "orderType": "Corretiva",
          "sector": "UTILIDADES 2",
          "equipment": "CALDEIRA TENGE",
          "tag": "CAL01602",
          "technicianId": "UTLME008",
          "date": "2026-04-04",
          "startTime": "01:00",
          "endTime": "04:00",
          "executedHours": 3,
          "activity": "Troca de válvula do cavalete.",
          "observation": "Efetuada troca de válvula, a mesma estava danificada devido ao fuso estar espanado, ok."
        },
        {
          "id": 69,
          "orderNumber": "10650777",
          "orderType": "Corretiva",
          "sector": "CREMES",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01663",
          "technicianId": "UTLME008",
          "date": "2026-04-07",
          "startTime": "18:00",
          "endTime": "21:00",
          "executedHours": 3,
          "activity": "TROCAR BOCAL DO BRACO",
          "observation": "Substituição do bocal do braço realizada, garantindo ajuste correto, vedação adequada e funcionamento seguro do equipamento."
        },
        {
          "id": 72,
          "orderNumber": "10650777",
          "orderType": "Corretiva",
          "sector": "CREMES",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01663",
          "technicianId": "UTLME005",
          "date": "2026-04-07",
          "startTime": "18:00",
          "endTime": "21:00",
          "executedHours": 3,
          "activity": "TROCAR BOCAL DO BRACO",
          "observation": "Substituição do bocal do braço realizada, garantindo ajuste correto, vedação adequada e funcionamento seguro do equipamento."
        },
        {
          "id": 78,
          "orderNumber": "10658723",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01629",
          "technicianId": "UTLRE007",
          "date": "2026-04-07",
          "startTime": "18:00",
          "endTime": "19:07",
          "executedHours": 1.12,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 79,
          "orderNumber": "10658724",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01630",
          "technicianId": "UTLRE007",
          "date": "2026-04-07",
          "startTime": "19:07",
          "endTime": "20:14",
          "executedHours": 1.12,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 80,
          "orderNumber": "10658725",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01631",
          "technicianId": "UTLRE007",
          "date": "2026-04-07",
          "startTime": "20:14",
          "endTime": "21:21",
          "executedHours": 1.12,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 70,
          "orderNumber": "10661891",
          "orderType": "Corretiva",
          "sector": "CREMES",
          "equipment": "ELEVADOR 2P 02",
          "tag": "ELE01614",
          "technicianId": "UTLME008",
          "date": "2026-04-07",
          "startTime": "21:00",
          "endTime": "00:00",
          "executedHours": 3,
          "activity": "ALINHAMENTO BARREIRA DE SEGURANCA",
          "observation": "Alinhamento da barreira de segurança e reset do sistema realizados, eliminando falha operacional e restabelecendo o funcionamento do elevador."
        },
        {
          "id": 73,
          "orderNumber": "10661891",
          "orderType": "Corretiva",
          "sector": "CREMES",
          "equipment": "ELEVADOR 2P 02",
          "tag": "ELE01614",
          "technicianId": "UTLME005",
          "date": "2026-04-07",
          "startTime": "21:00",
          "endTime": "00:00",
          "executedHours": 3,
          "activity": "ALINHAMENTO BARREIRA DE SEGURANCA",
          "observation": "Alinhamento da barreira de segurança e reset do sistema realizados, eliminando falha operacional e restabelecendo o funcionamento do elevador."
        },
        {
          "id": 81,
          "orderNumber": "10658726",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01632",
          "technicianId": "UTLRE007",
          "date": "2026-04-07",
          "startTime": "21:21",
          "endTime": "22:28",
          "executedHours": 1.12,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 82,
          "orderNumber": "10658727",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01633",
          "technicianId": "UTLRE007",
          "date": "2026-04-07",
          "startTime": "22:28",
          "endTime": "23:35",
          "executedHours": 1.12,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 71,
          "orderNumber": "10661892",
          "orderType": "Corretiva",
          "sector": "ETE",
          "equipment": "COMPRESSOR SOPRADOR 3",
          "tag": "COM01607",
          "technicianId": "UTLME008",
          "date": "2026-04-08",
          "startTime": "01:00",
          "endTime": "04:00",
          "executedHours": 3,
          "activity": "REESTABELECIMENTO DE EQUIPAMENTOS POS QUEDA DE ENERGIA",
          "observation": "Reestabelecimento dos equipamentos após queda de energia realizado, com normalização dos sistemas e retorno seguro da operação."
        },
        {
          "id": 74,
          "orderNumber": "10661892",
          "orderType": "Corretiva",
          "sector": "ETE",
          "equipment": "COMPRESSOR SOPRADOR 2",
          "tag": "COM01606",
          "technicianId": "UTLME005",
          "date": "2026-04-08",
          "startTime": "01:00",
          "endTime": "04:00",
          "executedHours": 3,
          "activity": "REESTABELECIMENTO DE EQUIPAMENTOS POS QUEDA DE ENERGIA",
          "observation": "Reestabelecimento dos equipamentos após queda de energia realizado, com normalização dos sistemas e retorno seguro da operação."
        },
        {
          "id": 83,
          "orderNumber": "10661892",
          "orderType": "Corretiva",
          "sector": "ETE",
          "equipment": "SOPRADOR 2",
          "tag": "COM01606",
          "technicianId": "UTLRE007",
          "date": "2026-04-08",
          "startTime": "01:00",
          "endTime": "04:00",
          "executedHours": 3,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 84,
          "orderNumber": "10658721",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01627",
          "technicianId": "UTLRE007",
          "date": "2026-04-08",
          "startTime": "04:00",
          "endTime": "04:55",
          "executedHours": 0.92,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 85,
          "orderNumber": "10658722",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01628",
          "technicianId": "UTLRE007",
          "date": "2026-04-08",
          "startTime": "04:55",
          "endTime": "05:50",
          "executedHours": 0.92,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 75,
          "orderNumber": "10661881",
          "orderType": "Corretiva",
          "sector": "ETE",
          "equipment": "MOTOBOMBA AUTO ESCORVANTE 1",
          "tag": "MOB01622",
          "technicianId": "UTLME005",
          "date": "2026-04-08",
          "startTime": "18:00",
          "endTime": "23:00",
          "executedHours": 5,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: realizado reparo valvula diafragma"
        },
        {
          "id": 86,
          "orderNumber": "10658718",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01624",
          "technicianId": "UTLRE007",
          "date": "2026-04-08",
          "startTime": "18:00",
          "endTime": "19:02",
          "executedHours": 1.03,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 96,
          "orderNumber": "10661881",
          "orderType": "Corretiva",
          "sector": "ETE",
          "equipment": "MOTOBOMBA AUTO ESCORVANTE 1",
          "tag": "MOB01622",
          "technicianId": "UTLME008",
          "date": "2026-04-08",
          "startTime": "18:00",
          "endTime": "23:00",
          "executedHours": 5,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: auxilio no bloq de energias"
        },
        {
          "id": 87,
          "orderNumber": "10658719",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01625",
          "technicianId": "UTLRE007",
          "date": "2026-04-08",
          "startTime": "19:02",
          "endTime": "20:04",
          "executedHours": 1.03,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 88,
          "orderNumber": "10658720",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01626",
          "technicianId": "UTLRE007",
          "date": "2026-04-08",
          "startTime": "20:04",
          "endTime": "21:06",
          "executedHours": 1.03,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 89,
          "orderNumber": "10658740",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01646",
          "technicianId": "UTLRE007",
          "date": "2026-04-08",
          "startTime": "21:06",
          "endTime": "22:18",
          "executedHours": 1.2,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 90,
          "orderNumber": "10658741",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01647",
          "technicianId": "UTLRE007",
          "date": "2026-04-08",
          "startTime": "22:18",
          "endTime": "23:30",
          "executedHours": 1.2,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 76,
          "orderNumber": "10662650",
          "orderType": "Corretiva",
          "sector": "ETE",
          "equipment": "MOTOBOMBA 1 RECIRCULACAO",
          "tag": "MOB01649",
          "technicianId": "UTLME005",
          "date": "2026-04-08",
          "startTime": "23:00",
          "endTime": "00:30",
          "executedHours": 1.5,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: REALIZADO A DESMONTAGEM DA TUBULAÇÃO"
        },
        {
          "id": 91,
          "orderNumber": "10658715",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01618",
          "technicianId": "UTLRE007",
          "date": "2026-04-09",
          "startTime": "01:00",
          "endTime": "01:58",
          "executedHours": 0.97,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 77,
          "orderNumber": "10662607",
          "orderType": "Corretiva",
          "sector": "UTILIDADES 1",
          "equipment": "CISTERNA 1 POTAVEL 30.000 L",
          "tag": "CIS01601",
          "technicianId": "UTLME005",
          "date": "2026-04-09",
          "startTime": "01:30",
          "endTime": "05:30",
          "executedHours": 4,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: REALIZADO A INSTALAÇÃO DO SUPORTE"
        },
        {
          "id": 97,
          "orderNumber": "10662607",
          "orderType": "Corretiva",
          "sector": "UTILIDADES 1",
          "equipment": "CISTERNA 1 POTAVEL 30.000 L",
          "tag": "CIS01601",
          "technicianId": "UTLME008",
          "date": "2026-04-09",
          "startTime": "01:30",
          "endTime": "05:30",
          "executedHours": 4,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: REALIZADO INSTALAÇÃO DA LUMINARIA E INFR"
        },
        {
          "id": 92,
          "orderNumber": "10658716",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01619",
          "technicianId": "UTLRE007",
          "date": "2026-04-09",
          "startTime": "01:58",
          "endTime": "02:56",
          "executedHours": 0.97,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 93,
          "orderNumber": "10658717",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01620",
          "technicianId": "UTLRE007",
          "date": "2026-04-09",
          "startTime": "02:56",
          "endTime": "03:58",
          "executedHours": 1.03,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 94,
          "orderNumber": "10658714",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01617",
          "technicianId": "UTLRE007",
          "date": "2026-04-09",
          "startTime": "03:58",
          "endTime": "04:53",
          "executedHours": 0.92,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 95,
          "orderNumber": "10658713",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01616",
          "technicianId": "UTLRE007",
          "date": "2026-04-09",
          "startTime": "04:53",
          "endTime": "05:56",
          "executedHours": 1.05,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 98,
          "orderNumber": "10536395",
          "orderType": "Preventiva",
          "sector": "PREDIO TI",
          "equipment": "PAINEL MAQUINA DISTRIBUICAO FAN COIL",
          "tag": "PMD01632",
          "technicianId": "UTLME008",
          "date": "2026-04-09",
          "startTime": "18:00",
          "endTime": "19:00",
          "executedHours": 1,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 100,
          "orderNumber": "10658709",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01612",
          "technicianId": "UTLRE007",
          "date": "2026-04-09",
          "startTime": "18:00",
          "endTime": "19:07",
          "executedHours": 1.12,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 101,
          "orderNumber": "10658710",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01613",
          "technicianId": "UTLRE007",
          "date": "2026-04-09",
          "startTime": "19:07",
          "endTime": "20:14",
          "executedHours": 1.12,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 102,
          "orderNumber": "10658711",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01614",
          "technicianId": "UTLRE007",
          "date": "2026-04-09",
          "startTime": "20:14",
          "endTime": "21:21",
          "executedHours": 1.12,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 103,
          "orderNumber": "10658708",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01611",
          "technicianId": "UTLRE007",
          "date": "2026-04-09",
          "startTime": "21:21",
          "endTime": "22:13",
          "executedHours": 0.87,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 99,
          "orderNumber": "10663002",
          "orderType": "Corretiva",
          "sector": "ETE",
          "equipment": "MOTOBOMBA AUTOESCORVANTE",
          "tag": "MOB01841",
          "technicianId": "UTLME008",
          "date": "2026-04-09",
          "startTime": "21:30",
          "endTime": "00:30",
          "executedHours": 3,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: REALIZADO ATENDIMENTO DE \"BARULHO\" ANORM"
        },
        {
          "id": 109,
          "orderNumber": "10663002",
          "orderType": "Corretiva",
          "sector": "ETE",
          "equipment": "MOTOBOMBA AUTOESCORVANTE",
          "tag": "MOB01841",
          "technicianId": "UTLME005",
          "date": "2026-04-09",
          "startTime": "21:30",
          "endTime": "00:30",
          "executedHours": 3,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: REALIZADO ATENDIMENTO DE \"BARULHO\" ANORM"
        },
        {
          "id": 104,
          "orderNumber": "10658712",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01615",
          "technicianId": "UTLRE007",
          "date": "2026-04-09",
          "startTime": "22:13",
          "endTime": "23:05",
          "executedHours": 0.87,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 105,
          "orderNumber": "10658707",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01610",
          "technicianId": "UTLRE007",
          "date": "2026-04-09",
          "startTime": "23:05",
          "endTime": "23:57",
          "executedHours": 0.87,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 106,
          "orderNumber": "10658706",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01609",
          "technicianId": "UTLRE007",
          "date": "2026-04-10",
          "startTime": "01:00",
          "endTime": "02:03",
          "executedHours": 1.05,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 107,
          "orderNumber": "10658705",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01608",
          "technicianId": "UTLRE007",
          "date": "2026-04-10",
          "startTime": "02:03",
          "endTime": "03:06",
          "executedHours": 1.05,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 108,
          "orderNumber": "10658704",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "BRACO EXTRATOR NEDERMAN",
          "tag": "BEX01607",
          "technicianId": "UTLRE007",
          "date": "2026-04-10",
          "startTime": "03:06",
          "endTime": "04:09",
          "executedHours": 1.05,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 110,
          "orderNumber": "10662583",
          "orderType": "Corretiva",
          "sector": "UTILIDADES 2",
          "equipment": "CALDEIRA TENGE",
          "tag": "CAL01602",
          "technicianId": "UTLME005",
          "date": "2026-04-10",
          "startTime": "03:30",
          "endTime": "05:00",
          "executedHours": 1.5,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: REALIZADO TROCA DE VALVULA DO CAVALETE"
        },
        {
          "id": 112,
          "orderNumber": "10663701",
          "orderType": "Corretiva",
          "sector": "UTILIDADES 1",
          "equipment": "PAINEL COMANDO CIS 1 E 2 ALIM PW",
          "tag": "PCM01615",
          "technicianId": "UTLME008",
          "date": "2026-04-13",
          "startTime": "18:00",
          "endTime": "05:00",
          "executedHours": 11,
          "activity": "INSTALACAO DE PRESSOSTATO",
          "observation": "Realizada instalação de pressostato para controle automático da bomba de água, garantindo operação dentro dos parâmetros de pressão. Executada montagem mecânica na linha e interligação elétrica em 24Vcc, substituindo sensor anterior por pressostato mecânico. Efetuados ajustes de liga/desliga conforme processo e realizados testes com simulação de pressão, confirmando acionamento e desligamento corretos. Sistema monitorado após intervenção, operando estável e sem falhas."
        },
        {
          "id": 113,
          "orderNumber": "10663701",
          "orderType": "Corretiva",
          "sector": "UTILIDADES 1",
          "equipment": "PAINEL COMANDO CIS 1 E 2 ALIM PW",
          "tag": "PCM01615",
          "technicianId": "UTLME005",
          "date": "2026-04-13",
          "startTime": "18:00",
          "endTime": "05:00",
          "executedHours": 11,
          "activity": "INSTALACAO DE PRESSOSTATO",
          "observation": "Realizada instalação de pressostato para controle automático da bomba de água, garantindo operação dentro dos parâmetros de pressão. Executada montagem mecânica na linha e interligação elétrica em 24Vcc, substituindo sensor anterior por pressostato mecânico. Efetuados ajustes de liga/desliga conforme processo e realizados testes com simulação de pressão, confirmando acionamento e desligamento corretos. Sistema monitorado após intervenção, operando estável e sem falhas."
        },
        {
          "id": 114,
          "orderNumber": "10663701",
          "orderType": "Corretiva",
          "sector": "UTILIDADES 1",
          "equipment": "PAINEL COMANDO CIS 1 E 2 ALIM PW",
          "tag": "PCM01615",
          "technicianId": "UTLRE007",
          "date": "2026-04-13",
          "startTime": "18:00",
          "endTime": "05:00",
          "executedHours": 11,
          "activity": "INSTALACAO DE PRESSOSTATO",
          "observation": "Realizada instalação de pressostato para controle automático da bomba de água, garantindo operação dentro dos parâmetros de pressão. Executada montagem mecânica na linha e interligação elétrica em 24Vcc, substituindo sensor anterior por pressostato mecânico. Efetuados ajustes de liga/desliga conforme processo e realizados testes com simulação de pressão, confirmando acionamento e desligamento corretos. Sistema monitorado após intervenção, operando estável e sem falhas."
        },
        {
          "id": 117,
          "orderNumber": "10661451",
          "orderType": "Preventiva",
          "sector": "ETE",
          "equipment": "COMPRESSOR SOPRADOR 2",
          "tag": "COM01606",
          "technicianId": "UTLME005",
          "date": "2026-04-14",
          "startTime": "18:00",
          "endTime": "20:00",
          "executedHours": 2,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: VERIFICADO E TROCADO OLEO"
        },
        {
          "id": 122,
          "orderNumber": "10660859",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "EXAUSTOR NEDERMAN",
          "tag": "EXA01601",
          "technicianId": "UTLRE007",
          "date": "2026-04-14",
          "startTime": "18:00",
          "endTime": "19:00",
          "executedHours": 1,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | AGUARDANDO FILTROS PARA TROCA"
        },
        {
          "id": 123,
          "orderNumber": "10661200",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "EXAUSTOR NEDERMAN",
          "tag": "EXA01602",
          "technicianId": "UTLRE007",
          "date": "2026-04-14",
          "startTime": "19:00",
          "endTime": "19:50",
          "executedHours": 0.83,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | AGUARDANDO FILTRO PARA TROCA"
        },
        {
          "id": 124,
          "orderNumber": "10661201",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "EXAUSTOR NEDERMAN",
          "tag": "EXA01603",
          "technicianId": "UTLRE007",
          "date": "2026-04-14",
          "startTime": "19:50",
          "endTime": "20:57",
          "executedHours": 1.12,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 118,
          "orderNumber": "10663790",
          "orderType": "Corretiva",
          "sector": "UTILIDADES 1",
          "equipment": "BOMBA CENTRIFUGA",
          "tag": "BOM01775",
          "technicianId": "UTLME005",
          "date": "2026-04-14",
          "startTime": "20:00",
          "endTime": "22:00",
          "executedHours": 2,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: RETIRADO VAZAMENTO DE AR COMPRIMIDO"
        },
        {
          "id": 115,
          "orderNumber": "10663791",
          "orderType": "Corretiva",
          "sector": "ETE",
          "equipment": "ESTUFA",
          "tag": "ESF01637",
          "technicianId": "UTLME008",
          "date": "2026-04-14",
          "startTime": "21:00",
          "endTime": "22:30",
          "executedHours": 1.5,
          "activity": "AJUSTE ALIMENTACAO DISJUNTOR",
          "observation": "Identificado desarme frequente no disjuntor do circuito da\nmufla da ETE durante operação conjunta. Carga total estimada\nem 5300 W (220 V), com corrente próxima de 24 A, acima da\nproteção existente de 16 A. Realizada transferência da\nalimentação para disjuntor de 25 A curva C no painel. Após\najuste, circuito testado e operando normalmente, sem novos\ndesarmes."
        },
        {
          "id": 120,
          "orderNumber": "10663791",
          "orderType": "Corretiva",
          "sector": "ETE",
          "equipment": "ESTUFA",
          "tag": "ESF01637",
          "technicianId": "UTLRE007",
          "date": "2026-04-14",
          "startTime": "21:00",
          "endTime": "23:30",
          "executedHours": 2.5,
          "activity": "AJUSTE ALIMENTACAO DISJUNTOR",
          "observation": "Identificado desarme frequente no disjuntor do circuito da\nmufla da ETE durante operação conjunta. Carga total estimada\nem 5300 W (220 V), com corrente próxima de 24 A, acima da\nproteção existente de 16 A. Realizada transferência da\nalimentação para disjuntor de 25 A curva C no painel. Após\najuste, circuito testado e operando normalmente, sem novos\ndesarmes."
        },
        {
          "id": 119,
          "orderNumber": "10660872",
          "orderType": "Preventiva",
          "sector": "ETE",
          "equipment": "COMPRESSOR SOPRADOR 1",
          "tag": "COM01605",
          "technicianId": "UTLME005",
          "date": "2026-04-14",
          "startTime": "22:00",
          "endTime": "04:00",
          "executedHours": 6,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | REAIZADO CARGA NA MOLA DA VALVULA | REALIZADO TROCA DO OLEO"
        },
        {
          "id": 125,
          "orderNumber": "10661968",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "FAN COIL AR-CONDICIONADO",
          "tag": "FAN01613",
          "technicianId": "UTLRE007",
          "date": "2026-04-14",
          "startTime": "22:30",
          "endTime": "00:27",
          "executedHours": 1.95,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 116,
          "orderNumber": "10663792",
          "orderType": "Corretiva",
          "sector": "CREMES",
          "equipment": "ELEVADOR CCME",
          "tag": "ELE01009",
          "technicianId": "UTLME008",
          "date": "2026-04-15",
          "startTime": "00:30",
          "endTime": "05:00",
          "executedHours": 4.5,
          "activity": "MESA DE ELEVACAO TRAVADA",
          "observation": "Realizado atendimento no equipamento, identificado travamento com rolos stretch no elevador, ocasionando parada do sistema.\nDurante a intervenção, foram removidos dois rolos para liberação do conjunto e restabelecimento do funcionamento do equipamento.\nApós a correção, o sistema foi testado e voltou a operar normalmente, sem anomalias no momento da liberação."
        },
        {
          "id": 121,
          "orderNumber": "10663792",
          "orderType": "Corretiva",
          "sector": "CREMES",
          "equipment": "ELEVADOR CCME",
          "tag": "ELE01009",
          "technicianId": "UTLRE007",
          "date": "2026-04-15",
          "startTime": "00:30",
          "endTime": "05:00",
          "executedHours": 4.5,
          "activity": "MESA DE ELEVACAO TRAVADA",
          "observation": "Realizado atendimento no equipamento, identificado travamento com rolos stretch no elevador, ocasionando parada do sistema.\nDurante a intervenção, foram removidos dois rolos para liberação do conjunto e restabelecimento do funcionamento do equipamento.\nApós a correção, o sistema foi testado e voltou a operar normalmente, sem anomalias no momento da liberação."
        },
        {
          "id": 126,
          "orderNumber": "10654509",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "PAINEL COMANDO BCS01, BCS02, BCP01",
          "tag": "PCM01632",
          "technicianId": "UTLME008",
          "date": "2026-04-15",
          "startTime": "18:00",
          "endTime": "19:15",
          "executedHours": 1.25,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | temperatura ok | 389 V - 397A disjuntor geral | troca de filtros ok"
        },
        {
          "id": 127,
          "orderNumber": "10664685",
          "orderType": "Corretiva",
          "sector": "CREMES",
          "equipment": "BECOMIX RW600 CD 2",
          "tag": "REA01412",
          "technicianId": "UTLME008",
          "date": "2026-04-15",
          "startTime": "18:00",
          "endTime": "20:00",
          "executedHours": 2,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: AUXILIO NA DRENAGEM DE CONDENSDO NA LINH"
        },
        {
          "id": 134,
          "orderNumber": "10664685",
          "orderType": "Corretiva",
          "sector": "CREMES",
          "equipment": "BECOMIX RW600 CD 2",
          "tag": "REA01412",
          "technicianId": "UTLME005",
          "date": "2026-04-15",
          "startTime": "18:00",
          "endTime": "20:00",
          "executedHours": 2,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: AUXILIO NA DRENAGEM DE CONDENSDO NA LINH"
        },
        {
          "id": 128,
          "orderNumber": "10654510",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "PAINEL COMANDO BCS3, BCM01, BCP02 E TORRES",
          "tag": "PCM01633",
          "technicianId": "UTLME008",
          "date": "2026-04-15",
          "startTime": "19:15",
          "endTime": "20:30",
          "executedHours": 1.25,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | temperatura ok | 389 V - 397A disjuntor geral | troca de filtros ok"
        },
        {
          "id": 136,
          "orderNumber": "10664686",
          "orderType": "Corretiva",
          "sector": "ETE",
          "equipment": "COMPRESSOR SOPRADOR 3",
          "tag": "COM01607",
          "technicianId": "UTLME005",
          "date": "2026-04-15",
          "startTime": "20:00",
          "endTime": "22:00",
          "executedHours": 2,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: REALIZADO INSTALAÇÃO E REGULAGEM DA VALV"
        },
        {
          "id": 129,
          "orderNumber": "10654511",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "PAINEL COMANDO BCS3, BCM01, BCP02 E TORRE",
          "tag": "PCM01634",
          "technicianId": "UTLME008",
          "date": "2026-04-15",
          "startTime": "20:30",
          "endTime": "21:45",
          "executedHours": 1.25,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | temperatura ok | 389 V - 397A disjuntor geral | troca de filtros ok"
        },
        {
          "id": 130,
          "orderNumber": "10654512",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "PAINEL COMANDO GERAL",
          "tag": "PCM01630",
          "technicianId": "UTLME008",
          "date": "2026-04-15",
          "startTime": "21:45",
          "endTime": "23:00",
          "executedHours": 1.25,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | temperatura ok | 389 V - 397A disjuntor geral | troca de filtros ok"
        },
        {
          "id": 137,
          "orderNumber": "10661452",
          "orderType": "Preventiva",
          "sector": "ETE",
          "equipment": "COMPRESSOR SOPRADOR 4",
          "tag": "COM01608",
          "technicianId": "UTLME005",
          "date": "2026-04-15",
          "startTime": "22:00",
          "endTime": "23:30",
          "executedHours": 1.5,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: REALIZADO VERIFICAÇÃO E TEMPERATURA"
        },
        {
          "id": 131,
          "orderNumber": "10664492",
          "orderType": "Corretiva",
          "sector": "ESCALONAMENTO",
          "equipment": "ELEVADOR 1",
          "tag": "ELE01616",
          "technicianId": "UTLME008",
          "date": "2026-04-15",
          "startTime": "23:00",
          "endTime": "01:30",
          "executedHours": 2.5,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: Realizado reposicionamento e alinhamento"
        },
        {
          "id": 135,
          "orderNumber": "10664492",
          "orderType": "Corretiva",
          "sector": "ESCALONAMENTO",
          "equipment": "ELEVADOR 1",
          "tag": "ELE01616",
          "technicianId": "UTLRE007",
          "date": "2026-04-15",
          "startTime": "23:00",
          "endTime": "01:30",
          "executedHours": 2.5,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: Realizado reposicionamento e alinhamento"
        },
        {
          "id": 138,
          "orderNumber": "10660873",
          "orderType": "Preventiva",
          "sector": "ETE",
          "equipment": "COMPRESSOR SOPRADOR 4",
          "tag": "COM01608",
          "technicianId": "UTLME005",
          "date": "2026-04-16",
          "startTime": "00:00",
          "endTime": "04:00",
          "executedHours": 4,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | VALVULA RETIRADA PARA AJUSTE NA USINAGEM | RPM TRAVADO EM 2000 CORRENTE ALTA"
        },
        {
          "id": 132,
          "orderNumber": "10654508",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "PAINEL COMANDO GERAL UTILIDADES MAKE",
          "tag": "PCM01629",
          "technicianId": "UTLME008",
          "date": "2026-04-16",
          "startTime": "02:30",
          "endTime": "03:40",
          "executedHours": 1.17,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | temperatura ok | 389 V - 397A disjuntor geral | feito troca de filtros ok"
        },
        {
          "id": 133,
          "orderNumber": "10654507",
          "orderType": "Preventiva",
          "sector": "MAKE",
          "equipment": "PAINEL COMANDO BCS04 E BCS5 (SECUNDARIO)",
          "tag": "PCM01631",
          "technicianId": "UTLME008",
          "date": "2026-04-16",
          "startTime": "03:40",
          "endTime": "04:50",
          "executedHours": 1.17,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | temperatura | 389 V - 397A disjuntor geral | troca de filtro ok | primario 220v sec 24v ok | sem falhas"
        },
        {
          "id": 141,
          "orderNumber": "10665364",
          "orderType": "Corretiva",
          "sector": "ETE",
          "equipment": "PHMETRO ENTRADA PRIMARIO",
          "tag": "PHM01640",
          "technicianId": "UTLME005",
          "date": "2026-04-19",
          "startTime": "18:00",
          "endTime": "18:10",
          "executedHours": 0.17,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: ok"
        },
        {
          "id": 168,
          "orderNumber": "10661967",
          "orderType": "Preventiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "FAN01612",
          "technicianId": "UTLRE007",
          "date": "2026-04-19",
          "startTime": "18:00",
          "endTime": "19:53",
          "executedHours": 1.88,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | NC"
        },
        {
          "id": 140,
          "orderNumber": "10665365",
          "orderType": "Corretiva",
          "sector": "ETE",
          "equipment": "MOTOBOMBA SUBMERSA 1 TANQUE PULMAO",
          "tag": "MOB01691",
          "technicianId": "UTLME008",
          "date": "2026-04-19",
          "startTime": "18:10",
          "endTime": "19:10",
          "executedHours": 1,
          "activity": "RETIRADO BOMBA DO CLARIFICADO",
          "observation": "A bomba do clarificado foi retirada para manutenção externa devido a um curto-circuito identificado."
        },
        {
          "id": 142,
          "orderNumber": "10665365",
          "orderType": "Corretiva",
          "sector": "ETE",
          "equipment": "MOTOBOMBA SUBMERSA 1 TANQUE PULMAO",
          "tag": "MOB01691",
          "technicianId": "UTLME005",
          "date": "2026-04-19",
          "startTime": "18:10",
          "endTime": "19:10",
          "executedHours": 1,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: RETIRADO BOMBA"
        },
        {
          "id": 143,
          "orderNumber": "10661450",
          "orderType": "Preventiva",
          "sector": "ETE",
          "equipment": "COMPRESSOR SOPRADOR 2",
          "tag": "COM01606",
          "technicianId": "UTLME005",
          "date": "2026-04-19",
          "startTime": "19:10",
          "endTime": "19:40",
          "executedHours": 0.5,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 139,
          "orderNumber": "10665366",
          "orderType": "Corretiva",
          "sector": "ETE",
          "equipment": "COMPRESSOR SOPRADOR 4",
          "tag": "COM01608",
          "technicianId": "UTLME008",
          "date": "2026-04-19",
          "startTime": "19:30",
          "endTime": "05:00",
          "executedHours": 9.5,
          "activity": "TROCA DE ELEMENTO SOPRADOR 4",
          "observation": "Foi realizada a troca do elemento soprador  4 devido à sua deterioração, que afetava a eficiência do sistema. O novo elemento foi instalado com sucesso, garantindo a continuidade das operações. Testes de funcionamento foram realizados, confirmando que o soprador opera dentro dos parâmetros estabelecidos."
        },
        {
          "id": 144,
          "orderNumber": "10660871",
          "orderType": "Preventiva",
          "sector": "ETE",
          "equipment": "COMPRESSOR SOPRADOR 2",
          "tag": "COM01606",
          "technicianId": "UTLME005",
          "date": "2026-04-19",
          "startTime": "19:40",
          "endTime": "21:40",
          "executedHours": 2,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | REALIZADO TROCA DE OLEO DO ELEMENTO | EQUIPAMENTO SEM VALVULA DE RETENÇÃO"
        },
        {
          "id": 169,
          "orderNumber": "10661158",
          "orderType": "Preventiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "FAN01603",
          "technicianId": "UTLRE007",
          "date": "2026-04-19",
          "startTime": "19:53",
          "endTime": "21:46",
          "executedHours": 1.88,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | NC"
        },
        {
          "id": 145,
          "orderNumber": "10661448",
          "orderType": "Preventiva",
          "sector": "ETE",
          "equipment": "COMPRESSOR SOPRADOR 1",
          "tag": "COM01605",
          "technicianId": "UTLME005",
          "date": "2026-04-19",
          "startTime": "21:40",
          "endTime": "22:10",
          "executedHours": 0.5,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 170,
          "orderNumber": "10661156",
          "orderType": "Preventiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "FAN01601",
          "technicianId": "UTLRE007",
          "date": "2026-04-19",
          "startTime": "21:46",
          "endTime": "23:39",
          "executedHours": 1.88,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | NC"
        },
        {
          "id": 146,
          "orderNumber": "10660870",
          "orderType": "Preventiva",
          "sector": "ETE",
          "equipment": "COMPRESSOR SOPRADOR 1",
          "tag": "COM01605",
          "technicianId": "UTLME005",
          "date": "2026-04-19",
          "startTime": "22:10",
          "endTime": "23:10",
          "executedHours": 1,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | EQUIPAMENTO SEM VALVULA DE RETENÇÃO"
        },
        {
          "id": 147,
          "orderNumber": "10665366",
          "orderType": "Corretiva",
          "sector": "ETE",
          "equipment": "COMPRESSOR SOPRADOR 4",
          "tag": "COM01608",
          "technicianId": "UTLME005",
          "date": "2026-04-20",
          "startTime": "00:00",
          "endTime": "05:00",
          "executedHours": 5,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: REALIZADO TROCA DO ELEMENTO 45 PELO 35,"
        },
        {
          "id": 171,
          "orderNumber": "10661157",
          "orderType": "Preventiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "FAN01602",
          "technicianId": "UTLRE007",
          "date": "2026-04-20",
          "startTime": "01:00",
          "endTime": "03:27",
          "executedHours": 2.45,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | NC"
        },
        {
          "id": 172,
          "orderNumber": "10661960",
          "orderType": "Preventiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "FAN01605",
          "technicianId": "UTLRE007",
          "date": "2026-04-20",
          "startTime": "03:27",
          "endTime": "05:54",
          "executedHours": 2.45,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | NC"
        },
        {
          "id": 148,
          "orderNumber": "10665523",
          "orderType": "Corretiva",
          "sector": "ETE",
          "equipment": "COMPRESSOR SOPRADOR 4",
          "tag": "COM01608",
          "technicianId": "UTLME005",
          "date": "2026-04-20",
          "startTime": "18:00",
          "endTime": "23:00",
          "executedHours": 5,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: REALIZADO AJUSTES"
        },
        {
          "id": 173,
          "orderNumber": "10661963",
          "orderType": "Preventiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "FAN01608",
          "technicianId": "UTLRE007",
          "date": "2026-04-20",
          "startTime": "18:00",
          "endTime": "20:06",
          "executedHours": 2.1,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | NC"
        },
        {
          "id": 153,
          "orderNumber": "10654516",
          "orderType": "Preventiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "PID01678",
          "technicianId": "UTLME008",
          "date": "2026-04-20",
          "startTime": "18:30",
          "endTime": "19:20",
          "executedHours": 0.83,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | 395V - 1,5A | ok temperatura normal | NA"
        },
        {
          "id": 154,
          "orderNumber": "10654517",
          "orderType": "Preventiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "PID01679",
          "technicianId": "UTLME008",
          "date": "2026-04-20",
          "startTime": "19:22",
          "endTime": "20:12",
          "executedHours": 0.83,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | 230 - 7,5A | Temperatura ok | NA"
        },
        {
          "id": 174,
          "orderNumber": "10661964",
          "orderType": "Preventiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "FAN01609",
          "technicianId": "UTLRE007",
          "date": "2026-04-20",
          "startTime": "20:06",
          "endTime": "22:12",
          "executedHours": 2.1,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | NC"
        },
        {
          "id": 155,
          "orderNumber": "10654514",
          "orderType": "Preventiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "PID01676",
          "technicianId": "UTLME008",
          "date": "2026-04-20",
          "startTime": "20:15",
          "endTime": "21:05",
          "executedHours": 0.83,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | 231V - 9,0A | Temperatura ok | NA"
        },
        {
          "id": 156,
          "orderNumber": "10654515",
          "orderType": "Preventiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "PID01677",
          "technicianId": "UTLME008",
          "date": "2026-04-20",
          "startTime": "21:10",
          "endTime": "22:03",
          "executedHours": 0.88,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | 225V - 6,2A | temperatura ok | NA"
        },
        {
          "id": 157,
          "orderNumber": "10654559",
          "orderType": "Preventiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "PCM01786",
          "technicianId": "UTLME008",
          "date": "2026-04-20",
          "startTime": "22:10",
          "endTime": "23:05",
          "executedHours": 0.92,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | 231V - 0,3A | ok temperatura normal | ok feito limpeza | NA"
        },
        {
          "id": 175,
          "orderNumber": "10661965",
          "orderType": "Preventiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "FAN01610",
          "technicianId": "UTLRE007",
          "date": "2026-04-20",
          "startTime": "22:12",
          "endTime": "00:18",
          "executedHours": 2.1,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | NC"
        },
        {
          "id": 158,
          "orderNumber": "10654560",
          "orderType": "Preventiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "PCM01787",
          "technicianId": "UTLME008",
          "date": "2026-04-20",
          "startTime": "23:05",
          "endTime": "23:55",
          "executedHours": 0.83,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | 230V - 0,1A | ok temperatura normal | NA"
        },
        {
          "id": 149,
          "orderNumber": "10665374",
          "orderType": "Corretiva",
          "sector": "CREMES",
          "equipment": "ELEVADOR CCME",
          "tag": "ELE01009",
          "technicianId": "UTLME005",
          "date": "2026-04-21",
          "startTime": "01:00",
          "endTime": "04:00",
          "executedHours": 3,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: AJUSTADO SENSOR OK"
        },
        {
          "id": 159,
          "orderNumber": "10665374",
          "orderType": "Corretiva",
          "sector": "CREMES",
          "equipment": "ELEVADOR CCME",
          "tag": "ELE01009",
          "technicianId": "UTLME008",
          "date": "2026-04-21",
          "startTime": "01:00",
          "endTime": "04:00",
          "executedHours": 3,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: AJUSTADO SENSOR OK"
        },
        {
          "id": 176,
          "orderNumber": "10661966",
          "orderType": "Preventiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "FAN01611",
          "technicianId": "UTLRE007",
          "date": "2026-04-21",
          "startTime": "01:18",
          "endTime": "03:19",
          "executedHours": 2.02,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | NC"
        },
        {
          "id": 177,
          "orderNumber": "10661962",
          "orderType": "Preventiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "FAN01607",
          "technicianId": "UTLRE007",
          "date": "2026-04-21",
          "startTime": "03:19",
          "endTime": "05:20",
          "executedHours": 2.02,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | NC"
        },
        {
          "id": 160,
          "orderNumber": "10654505",
          "orderType": "Preventiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "PAI01648",
          "technicianId": "UTLME008",
          "date": "2026-04-21",
          "startTime": "04:10",
          "endTime": "05:03",
          "executedHours": 0.88,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | temperatura ok | 399 V - 12A | nao se aplica"
        },
        {
          "id": 150,
          "orderNumber": "10665522",
          "orderType": "Corretiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "CXA01613",
          "technicianId": "UTLME005",
          "date": "2026-04-21",
          "startTime": "18:00",
          "endTime": "21:00",
          "executedHours": 3,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: REALIZADO A TROCA DA BOIA QUE ESTAVA DAN"
        },
        {
          "id": 161,
          "orderNumber": "10665522",
          "orderType": "Corretiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "CXA01613",
          "technicianId": "UTLME008",
          "date": "2026-04-21",
          "startTime": "18:00",
          "endTime": "21:00",
          "executedHours": 3,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: AUXILIO NA RESOLUSAO DO VAZAMENTO"
        },
        {
          "id": 178,
          "orderNumber": "10665522",
          "orderType": "Corretiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "CXA01613",
          "technicianId": "UTLRE007",
          "date": "2026-04-21",
          "startTime": "18:00",
          "endTime": "21:00",
          "executedHours": 3,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: AUXILIO NA RESOLUSAO DO VAZAMENTO"
        },
        {
          "id": 151,
          "orderNumber": "10665524",
          "orderType": "Corretiva",
          "sector": "CREMES",
          "equipment": "ELEVADOR 2P 02",
          "tag": "ELE01614",
          "technicianId": "UTLME005",
          "date": "2026-04-21",
          "startTime": "21:00",
          "endTime": "23:00",
          "executedHours": 2,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: CONFECCIONADO"
        },
        {
          "id": 179,
          "orderNumber": "10661159",
          "orderType": "Preventiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "FAN01604",
          "technicianId": "UTLRE007",
          "date": "2026-04-21",
          "startTime": "21:00",
          "endTime": "23:27",
          "executedHours": 2.45,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | NC"
        },
        {
          "id": 162,
          "orderNumber": "10654506",
          "orderType": "Preventiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "PAI01653",
          "technicianId": "UTLME008",
          "date": "2026-04-21",
          "startTime": "21:20",
          "endTime": "22:20",
          "executedHours": 1,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | temperatura ok | 398 V - 1,5A | troca de fltro ok"
        },
        {
          "id": 163,
          "orderNumber": "10654513",
          "orderType": "Preventiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "PAI01660",
          "technicianId": "UTLME008",
          "date": "2026-04-21",
          "startTime": "22:30",
          "endTime": "23:33",
          "executedHours": 1.05,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | temperatura ok | 392 V - 1,3A | troca de fltro ok | sem falhas"
        },
        {
          "id": 152,
          "orderNumber": "10665525",
          "orderType": "Corretiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "FAN01608",
          "technicianId": "UTLME005",
          "date": "2026-04-21",
          "startTime": "23:00",
          "endTime": "02:00",
          "executedHours": 3,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: REALIZADO"
        },
        {
          "id": 164,
          "orderNumber": "10654558",
          "orderType": "Preventiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "PCM01780",
          "technicianId": "UTLME008",
          "date": "2026-04-22",
          "startTime": "01:00",
          "endTime": "01:50",
          "executedHours": 0.83,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | 397V - 6,5A | ok feito limpeza | NA"
        },
        {
          "id": 180,
          "orderNumber": "10661961",
          "orderType": "Preventiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "FAN01606",
          "technicianId": "UTLRE007",
          "date": "2026-04-22",
          "startTime": "01:00",
          "endTime": "03:16",
          "executedHours": 2.27,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | NC"
        },
        {
          "id": 165,
          "orderNumber": "10654556",
          "orderType": "Preventiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "PCM01706",
          "technicianId": "UTLME008",
          "date": "2026-04-22",
          "startTime": "02:00",
          "endTime": "03:00",
          "executedHours": 1,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | 397 V - 1,8A | temperatura ok | troca de filtro ok"
        },
        {
          "id": 166,
          "orderNumber": "10654557",
          "orderType": "Preventiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "PCM01707",
          "technicianId": "UTLME008",
          "date": "2026-04-22",
          "startTime": "03:00",
          "endTime": "04:00",
          "executedHours": 1,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK | 397 V - 1,8A | temperatura ok | troca de filtro ok"
        },
        {
          "id": 181,
          "orderNumber": "10661432",
          "orderType": "Preventiva",
          "sector": "PENDENTE SAP",
          "equipment": "PENDENTE SAP",
          "tag": "CHI01603",
          "technicianId": "UTLRE007",
          "date": "2026-04-22",
          "startTime": "03:16",
          "endTime": "04:00",
          "executedHours": 0.73,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: OK"
        },
        {
          "id": 167,
          "orderNumber": "10665682",
          "orderType": "Corretiva",
          "sector": "HIDRO",
          "equipment": "ELEVADOR DO HIDRO",
          "tag": "ELE01012",
          "technicianId": "UTLME008",
          "date": "2026-04-22",
          "startTime": "04:00",
          "endTime": "04:55",
          "executedHours": 0.92,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: alinhado sensor, ok"
        },
        {
          "id": 182,
          "orderNumber": "10665682",
          "orderType": "Corretiva",
          "sector": "HIDRO",
          "equipment": "ELEVADOR DO HIDRO",
          "tag": "ELE01012",
          "technicianId": "UTLRE007",
          "date": "2026-04-22",
          "startTime": "04:00",
          "endTime": "04:55",
          "executedHours": 0.92,
          "activity": "IMPORTACAO SAP - PREENCHER",
          "observation": "Confirmação SAP: alinhado sensor, ok"
        }
      ]
    }
  }
}
